function mapclass_euro = create_mapping_euro()
keySet_euro = [10, 11, 12, 13, 14, 15, 16];
valueSet_euro = {'20euro',...
                 '10euro',...
                 '10euro',...
                 '5euro',...
                 '50euro',...
                 '5euro',...
                 '100euro'};
mapclass_euro = containers.Map(keySet_euro, valueSet_euro);